### ISSUE TITLE
ModuleNotFoundError: No module named 'wakatime.project'

### ISSUE THREAD

**Issue by andre-paulo98** [wakatime/sublime-wakatime#102]
I recently formatted my computer, and tried to install Wakatime again but it doesn't seem to be working so well this time.

```
[WakaTime] [DEBUG] pythonw C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\cli.py --entity C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\User\WakaTime.sublime-settings --time 1595096301.702407 --plugin sublime/3211 sublime-wakatime/9.1.2 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX835d --cursorpos 1 --exclude ^/tmp/ --exclude ^/etc/ --exclude ^/var/(?!www/).* --exclude COMMIT_EDITMSG$ --exclude PULLREQ_EDITMSG$ --exclude MERGE_MSG$ --exclude TAG_EDITMSG$ --include .* --verbose
[WakaTime] [ERROR] wakatime-core exited with status: 1
[WakaTime] [ERROR] wakatime-core output: Traceback (most recent call last):

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\cli.py", line 24, in <module>

    import wakatime

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\__init__.py", line 17, in <module>

    from .main import execute

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\main.py", line 32, in <module>

    from .api import send_heartbeats, get_time_today

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\api.py", line 21, in <module>

    from .offlinequeue import Queue

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\offlinequeue.py", line 19, in <module>

    from .heartbeat import Heartbeat

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\heartbeat.py", line 17, in <module>

    from .project import get_project_info

ModuleNotFoundError: No module named 'wakatime.project'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\cli.py", line 31, in <module>

    import wakatime

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\__init__.py", line 17, in <module>

    from .main import execute

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\main.py", line 32, in <module>

    from .api import send_heartbeats, get_time_today

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\api.py", line 21, in <module>

    from .offlinequeue import Queue

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\offlinequeue.py", line 19, in <module>

    from .heartbeat import Heartbeat

  File "C:\Users\andre\AppData\Roaming\Sublime Text 3\Packages\WakaTime\packages\wakatime\heartbeat.py", line 17, in <module>

    from .project import get_project_info

ModuleNotFoundError: No module named 'wakatime.project'
```

I've also tried to use in other programs (PHPStorm, IntelliJ) and they seem to work **only while debug is active**. I get a warning that it might be slower because of debug but it seems to work.

**Comment by alanhamlett** [comment]
Is this still happening? Can you try re-installing the plugin?

**Comment by gandarez** [comment]
@alanhamlett should we close this issue and reopen when reported again?

**Comment by andre-paulo98** [comment]
I think after a few reinstalls I got it to working again.
Not sure what was the problem.
Sorry for not closing this earlier
