### ISSUE TITLE
SublimeText plugin wakatime-cli update error

### ISSUE THREAD

**Issue by mcwnuq** [wakatime/sublime-wakatime#107]
Hi,
Recently, I noticed that SublimeText is not reporting data to WakaTime.
 I turned on debugging and found such an error (every time I run ST).

```
[WakaTime] [INFO] Initializing WakaTime plugin v11.0.2
[WakaTime] [INFO] Current wakatime-cli version is v1.30.5
[WakaTime] [INFO] Checking for updates to wakatime-cli...
[WakaTime] [DEBUG] GitHub API Response 304
[WakaTime] [INFO] Found an updated wakatime-cli v1
[WakaTime] [INFO] Downloading wakatime-cli...
[WakaTime] [DEBUG] Downloading wakatime-cli from https://github.com/wakatime/wakatime-cli/releases/download/v1
[WakaTime] [DEBUG] Traceback (most recent call last):
  File "C:\Users\mcwnuq\AppData\Roaming\Sublime Text 3\Packages\WakaTime\WakaTime.py", line 639, in run
    download(url, zip_file)
  File "C:\Users\mcwnuq\AppData\Roaming\Sublime Text 3\Packages\WakaTime\WakaTime.py", line 892, in download
    urlretrieve(url, filePath)
  File "./python3.3/urllib/request.py", line 181, in urlretrieve
  File "./python3.3/urllib/request.py", line 156, in urlopen
  File "./python3.3/urllib/request.py", line 475, in open
  File "./python3.3/urllib/request.py", line 587, in http_response
  File "./python3.3/urllib/request.py", line 513, in error
  File "./python3.3/urllib/request.py", line 447, in _call_chain
  File "./python3.3/urllib/request.py", line 595, in http_error_default
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by alanhamlett** [comment]
Try deleting the file at `C:\Users\mcwnuq\.wakatime-internal.cfg` and then restart Sublime Text.

**Comment by mcwnuq** [comment]
Thanks for the advice. I did as you said and now it works. Thank you very much for help. :)
