### ISSUE TITLE
Exception when enabling the package

### ISSUE THREAD

**Issue by rchl** [wakatime/sublime-wakatime#113]
I had WakaTime package disabled in the current session and decide to enable it using `Package Control: Enable package`. That resulted in the following error in the ST console:

```
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "/Users/../Library/Application Support/Sublime Text/Packages/WakaTime/WakaTime.py", line 674, in run
    createSymlink()
  File "/Users/../Library/Application Support/Sublime Text/Packages/WakaTime/WakaTime.py", line 966, in createSymlink
    log(traceback.format_exc())
TypeError: log() missing 1 required positional argument: 'message'
```

I think all is working fine after restarting ST but in any case that pointed out line seems wrong.

**Comment by alanhamlett** [comment]
Fixed with e15c514ef3f0d15536fd33dca3caa3c5f1c121e7.
