### ISSUE TITLE
Exception in thread Thread

### ISSUE THREAD

**Issue by thecotne** [wakatime/sublime-wakatime#39]
```
Exception in thread Thread-149:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "C:\Users\cotne\AppData\Roaming\Sublime Text 3\Packages\WakaTime\WakaTime.py", line 205, in run
    self.send_heartbeat()
  File "C:\Users\cotne\AppData\Roaming\Sublime Text 3\Packages\WakaTime\WakaTime.py", line 224, in send_heartbeat
    project_name = find_project_from_folders(self.folders, self.target_file)
  File "C:\Users\cotne\AppData\Roaming\Sublime Text 3\Packages\WakaTime\WakaTime.py", line 171, in find_project_from_folders
    return os.path.basename(folder)
  File "./ntpath.py", line 309, in basename
  File "./ntpath.py", line 280, in split
  File "./ntpath.py", line 208, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

i don't now that this is but it's clearly wakatime bug

i have 
ST 3082 
win7
Python 3.4.3

**Comment by alanhamlett** [comment]
Fixed in v3.0.19 with b6c4956521f05db2615b03794f3e3404c43e18ad.

Thanks!
