### ISSUE TITLE
Sublime Text 2.0.2 thread error

### ISSUE THREAD

**Issue by billyrud** [wakatime/sublime-wakatime#63]
Looks like the plugin is not working on sublime text 2.0.2, this issue looks like it was fixed back in ticket #34 but somewhere along the line it showed up again. The WakaTime version I have installed is 6.0.6.

Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\WakaTime.py", line 389, in run
  File ".\WakaTime.py", line 417, in send_heartbeat
  File ".\WakaTime.py", line 192, in python_binary
  File ".\WakaTime.py", line 215, in find_python_from_registry
  File ".\WakaTime.py", line 259, in find_python_from_registry
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

**Comment by alanhamlett** [comment]
Fixed in v6.0.7 with c64f125dc483ebdf44b584a0584fe43fb2ad4779.

Thank you!
