### ISSUE TITLE
something wrong in my sublime3

### ISSUE THREAD

**Issue by RanchoCooper** [wakatime/sublime-wakatime#65]
Recently I install wakatime plugin via package control
at first it works good, but Today I find out 'wakatime error' at sublime's state bar

following error code from console:

```
[WakaTime] [ERROR] wakatime-core exited with status: 1
[WakaTime] [ERROR] wakatime-core output: Traceback (most recent call last):

  File "E:\Sublime Text 3\Data\Packages\WakaTime\packages\wakatime\cli.py", line 31, in <module>

    import wakatime

  File "E:\Sublime Text 3\Data\Packages\WakaTime\packages\wakatime\__init__.py", line 17, in <module>

    from .main import execute

  File "E:\Sublime Text 3\Data\Packages\WakaTime\packages\wakatime\main.py", line 22, in <module>

    import socket

  File "E:\Python27\lib\socket.py", line 47, in <module>

    import _socket

ImportError: Module use of python33.dll conflicts with this version of Python.


```

**Comment by alanhamlett** [comment]
Looks like a corrupted Python installation. Can you try installing Python manually from https://www.python.org/downloads/ and restart Sublime Text?

**Comment by RanchoCooper** [comment]
:(  after remove Python
restart sublime3 derectly, seems extrat py from zip in sublime folder
then it's ok
puzzle....
