### ISSUE TITLE
MissingSectionHeaderError: File contains no section headers.

### ISSUE THREAD

**Issue by mibzman** [wakatime/sublime-wakatime#73]
I used wakatime sucessfully in sublime 3 on mac, but now whenever wakatime refreshes I get this error.

```
[WakaTime] [DEBUG] pythonw /Users/user/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/cli.py --entity /Users/user/go/src/27thisotope.ddns.net/mibzman/projectname/mobile/config.xml --time 1498671259.072659 --plugin sublime/3126 sublime-wakatime/7.0.22 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXe036 --alternate-project projectname --cursorpos 5655 --exclude ^/tmp/ --exclude ^/etc/ --exclude ^/var/(?!www/).* --exclude COMMIT_EDITMSG$ --exclude PULLREQ_EDITMSG$ --exclude MERGE_MSG$ --exclude TAG_EDITMSG$ --verbose
[WakaTime] [ERROR] wakatime-core exited with status: 103
[WakaTime] [ERROR] wakatime-core output: Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/configs.py", line 58, in parseConfigFile
    configs.read_file(fh)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/configparser/__init__.py", line 724, in read_file
    self._read(f, source)
  File "/Users/user/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/configparser/__init__.py", line 1101, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: '/Users/user/.wakatime.cfg', line: 1
u'b3e3685b-56b0-4877-a0c1-ca7c128ce036\n'

```

I believe this issue began when I tried to install wakatime for terminal.  I have no problem removing the terminal plugin, since I don't really need it.

Is there an easy way to completly remove wakatime from my system and re-add it in sublime?

**Comment by vanesa** [comment]
Hi, try deleting this file /Users/user/.wakatime.cfg and restart Sublime.

**Comment by mibzman** [comment]
Thanks!  That did the trick!
