### ISSUE TITLE
Invalid proxy

### ISSUE THREAD

**Issue by LinTeX9527** [wakatime/sublime-wakatime#80]
I just set "api_key" in `WakaTime.sublime-settings`, and no personal settings for  "proxy", this is what I got:

```
reloading settings Packages/User/WakaTime.sublime-settings
[WakaTime] [DEBUG] pythonw C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\cli.py --entity C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\WakaTime.sublime-settings --time 1515394837.857341 --plugin sublime/3143 sublime-wakatime/7.0.17 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX0a1a --cursorpos 330 --ignore ^/tmp/ --ignore ^/etc/ --ignore ^/var/ --ignore COMMIT_EDITMSG$ --ignore PULLREQ_EDITMSG$ --ignore MERGE_MSG$ --ignore TAG_EDITMSG$ --verbose
[WakaTime] [ERROR] wakatime-core exited with status: 2
[WakaTime] [ERROR] wakatime-core output: usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]

                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]

                [--entity-type ENTITY_TYPE] [--proxy PROXY]

                [--project PROJECT] [--alternate-project ALTERNATE_PROJECT]

                [--language LANGUAGE] [--hostname HOSTNAME] [--disableoffline]

                [--hidefilenames] [--exclude EXCLUDE] [--include INCLUDE]

                [--extra-heartbeats] [--logfile LOGFILE] [--apiurl API_URL]

                [--timeout TIMEOUT] [--config CONFIG] [--verbose] [--version]

wakatime: error: Invalid proxy. Must be in format https://user:pass@host:port or socks5://user:pass@host:port or domain\user:pass.

```

**Comment by alanhamlett** [comment]
Another place the proxy could be defined is in your `~/.wakatime.cfg` file. Is there a proxy defined there?

**Comment by LinTeX9527** [comment]
@alanhamlett Thanks.

There was a proxy defined here. I deleted this file, restarted sublime but got another error.

```
reloading settings Packages/User/WakaTime.sublime-settings
[WakaTime] [DEBUG] pythonw C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\cli.py --entity C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\User\WakaTime.sublime-settings --time 1515466760.621104 --plugin sublime/3143 sublime-wakatime/8.0.6 --key XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX0a1a --cursorpos 132 --exclude ^/tmp/ --exclude ^/etc/ --exclude ^/var/(?!www/).* --exclude COMMIT_EDITMSG$ --exclude PULLREQ_EDITMSG$ --exclude MERGE_MSG$ --exclude TAG_EDITMSG$ --include .* --verbose
[WakaTime] [ERROR] wakatime-core output: Traceback (most recent call last):

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 861, in emit

    msg = self.format(record)

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 734, in format

    return fmt.format(record)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\logger.py", line 56, in format

    return json.dumps(data)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\__init__.py", line 380, in dumps

    return _default_encoder.encode(obj)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 277, in encode

    chunks = list(chunks)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 655, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 584, in _iterencode_dict

    yield _encoder(value)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 66, in py_encode_basestring_ascii

    s = s.decode('utf-8')

  File "D:\Program Files\Anaconda2\lib\encodings\utf_8.py", line 16, in decode

    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 20: invalid continuation byte

Logged from file logger.py, line 62

Traceback (most recent call last):

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 861, in emit

    msg = self.format(record)

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 734, in format

    return fmt.format(record)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\logger.py", line 56, in format

    return json.dumps(data)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\__init__.py", line 380, in dumps

    return _default_encoder.encode(obj)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 277, in encode

    chunks = list(chunks)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 655, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 584, in _iterencode_dict

    yield _encoder(value)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 66, in py_encode_basestring_ascii

    s = s.decode('utf-8')

  File "D:\Program Files\Anaconda2\lib\encodings\utf_8.py", line 16, in decode

    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 20: invalid continuation byte

Logged from file api.py, line 53

Traceback (most recent call last):

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 861, in emit

    msg = self.format(record)

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 734, in format

    return fmt.format(record)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\logger.py", line 56, in format

    return json.dumps(data)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\__init__.py", line 380, in dumps

    return _default_encoder.encode(obj)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 277, in encode

    chunks = list(chunks)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 655, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 584, in _iterencode_dict

    yield _encoder(value)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 66, in py_encode_basestring_ascii

    s = s.decode('utf-8')

  File "D:\Program Files\Anaconda2\lib\encodings\utf_8.py", line 16, in decode

    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 20: invalid continuation byte

Logged from file api.py, line 59

Traceback (most recent call last):

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 861, in emit

    msg = self.format(record)

  File "D:\Program Files\Anaconda2\lib\logging\__init__.py", line 734, in format

    return fmt.format(record)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\logger.py", line 56, in format

    return json.dumps(data)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\__init__.py", line 380, in dumps

    return _default_encoder.encode(obj)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 277, in encode

    chunks = list(chunks)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 655, in _iterencode

    for chunk in _iterencode_dict(o, _current_indent_level):

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 584, in _iterencode_dict

    yield _encoder(value)

  File "C:\Users\Administrator\AppData\Roaming\Sublime Text 3\Packages\wakatime\packages\wakatime\packages\simplejson\encoder.py", line 66, in py_encode_basestring_ascii

    s = s.decode('utf-8')

  File "D:\Program Files\Anaconda2\lib\encodings\utf_8.py", line 16, in decode

    return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 20: invalid continuation byte

Logged from file api.py, line 165

```

Then I disabled the debug option, problem solved. 
![image](https://user-images.githubusercontent.com/10264703/34703180-9090fd76-f52c-11e7-9a28-4bc5f6549bda.png)
