### ISSUE TITLE
ModuleNotFoundError: No module named 'zlib'

### ISSUE THREAD

**Issue by BryanJBryce** [wakatime/sublime-wakatime#89]
SublimeText 3.1.1 for macOS

```
[WakaTime] [ERROR] wakatime-core exited with status: 1
[WakaTime] [ERROR] wakatime-core output: Traceback (most recent call last):
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/cli.py", line 24, in <module>
    import wakatime
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/__init__.py", line 17, in <module>
    from .main import execute
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/main.py", line 24, in <module>
    from .api import send_heartbeats
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/api.py", line 22, in <module>
    from .packages.requests.exceptions import RequestException
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/urllib3/connectionpool.py", line 36, in <module>
    from .response import HTTPResponse
  File "/Users/bryan/Library/Application Support/Sublime Text 3/Packages/WakaTime/packages/wakatime/packages/urllib3/response.py", line 3, in <module>
    import zlib
ModuleNotFoundError: No module named 'zlib'
```

**Comment by alanhamlett** [comment]
This looks like a problem with `zlib` library on the default Python for your machine. What version of Python is in your PATH? You can check with this command: `python --version`.

**Comment by alanhamlett** [comment]
Fixed now that we're using Go instead of Python for wakatime-cli.
